# Generated by Django 4.2.20 on 2026-01-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0002_robotcomponent_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotAxisData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="部件编号"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="时间戳"),
                ),
                ("snr_c", models.IntegerField(db_index=True, verbose_name="SNR_C")),
                (
                    "p_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="程序名称"
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="参考编号"
                    ),
                ),
                (
                    "robot_stop",
                    models.BooleanField(default=False, verbose_name="机器人停止"),
                ),
                (
                    "curr_a1",
                    models.FloatField(blank=True, null=True, verbose_name="A1电流"),
                ),
                (
                    "curr_a2",
                    models.FloatField(blank=True, null=True, verbose_name="A2电流"),
                ),
                (
                    "curr_a3",
                    models.FloatField(blank=True, null=True, verbose_name="A3电流"),
                ),
                (
                    "curr_a4",
                    models.FloatField(blank=True, null=True, verbose_name="A4电流"),
                ),
                (
                    "curr_a5",
                    models.FloatField(blank=True, null=True, verbose_name="A5电流"),
                ),
                (
                    "curr_a6",
                    models.FloatField(blank=True, null=True, verbose_name="A6电流"),
                ),
                (
                    "curr_e1",
                    models.FloatField(blank=True, null=True, verbose_name="E1电流"),
                ),
                (
                    "max_curr_a1",
                    models.FloatField(blank=True, null=True, verbose_name="A1最大电流"),
                ),
                (
                    "max_curr_a2",
                    models.FloatField(blank=True, null=True, verbose_name="A2最大电流"),
                ),
                (
                    "max_curr_a3",
                    models.FloatField(blank=True, null=True, verbose_name="A3最大电流"),
                ),
                (
                    "max_curr_a4",
                    models.FloatField(blank=True, null=True, verbose_name="A4最大电流"),
                ),
                (
                    "max_curr_a5",
                    models.FloatField(blank=True, null=True, verbose_name="A5最大电流"),
                ),
                (
                    "max_curr_a6",
                    models.FloatField(blank=True, null=True, verbose_name="A6最大电流"),
                ),
                (
                    "max_curr_e1",
                    models.FloatField(blank=True, null=True, verbose_name="E1最大电流"),
                ),
                (
                    "min_curr_a1",
                    models.FloatField(blank=True, null=True, verbose_name="A1最小电流"),
                ),
                (
                    "min_curr_a2",
                    models.FloatField(blank=True, null=True, verbose_name="A2最小电流"),
                ),
                (
                    "min_curr_a3",
                    models.FloatField(blank=True, null=True, verbose_name="A3最小电流"),
                ),
                (
                    "min_curr_a4",
                    models.FloatField(blank=True, null=True, verbose_name="A4最小电流"),
                ),
                (
                    "min_curr_a5",
                    models.FloatField(blank=True, null=True, verbose_name="A5最小电流"),
                ),
                (
                    "min_curr_a6",
                    models.FloatField(blank=True, null=True, verbose_name="A6最小电流"),
                ),
                (
                    "min_curr_e1",
                    models.FloatField(blank=True, null=True, verbose_name="E1最小电流"),
                ),
                (
                    "tem_1",
                    models.IntegerField(blank=True, null=True, verbose_name="A1温度"),
                ),
                (
                    "tem_2",
                    models.IntegerField(blank=True, null=True, verbose_name="A2温度"),
                ),
                (
                    "tem_3",
                    models.IntegerField(blank=True, null=True, verbose_name="A3温度"),
                ),
                (
                    "tem_4",
                    models.IntegerField(blank=True, null=True, verbose_name="A4温度"),
                ),
                (
                    "tem_5",
                    models.IntegerField(blank=True, null=True, verbose_name="A5温度"),
                ),
                (
                    "tem_6",
                    models.IntegerField(blank=True, null=True, verbose_name="A6温度"),
                ),
                (
                    "tem_7",
                    models.IntegerField(blank=True, null=True, verbose_name="E1温度"),
                ),
                (
                    "axisp1",
                    models.FloatField(blank=True, null=True, verbose_name="A1位置"),
                ),
                (
                    "axisp2",
                    models.FloatField(blank=True, null=True, verbose_name="A2位置"),
                ),
                (
                    "axisp3",
                    models.FloatField(blank=True, null=True, verbose_name="A3位置"),
                ),
                (
                    "axisp4",
                    models.FloatField(blank=True, null=True, verbose_name="A4位置"),
                ),
                (
                    "axisp5",
                    models.FloatField(blank=True, null=True, verbose_name="A5位置"),
                ),
                (
                    "axisp6",
                    models.FloatField(blank=True, null=True, verbose_name="A6位置"),
                ),
                (
                    "axisp7",
                    models.FloatField(blank=True, null=True, verbose_name="E1位置"),
                ),
                (
                    "speed1",
                    models.FloatField(blank=True, null=True, verbose_name="A1速度"),
                ),
                (
                    "speed2",
                    models.FloatField(blank=True, null=True, verbose_name="A2速度"),
                ),
                (
                    "speed3",
                    models.FloatField(blank=True, null=True, verbose_name="A3速度"),
                ),
                (
                    "speed4",
                    models.FloatField(blank=True, null=True, verbose_name="A4速度"),
                ),
                (
                    "speed5",
                    models.FloatField(blank=True, null=True, verbose_name="A5速度"),
                ),
                (
                    "speed6",
                    models.FloatField(blank=True, null=True, verbose_name="A6速度"),
                ),
                (
                    "speed7",
                    models.FloatField(blank=True, null=True, verbose_name="E7速度"),
                ),
                (
                    "torque1",
                    models.FloatField(blank=True, null=True, verbose_name="A1扭矩"),
                ),
                (
                    "torque2",
                    models.FloatField(blank=True, null=True, verbose_name="A2扭矩"),
                ),
                (
                    "torque3",
                    models.FloatField(blank=True, null=True, verbose_name="A3扭矩"),
                ),
                (
                    "torque4",
                    models.FloatField(blank=True, null=True, verbose_name="A4扭矩"),
                ),
                (
                    "torque5",
                    models.FloatField(blank=True, null=True, verbose_name="A5扭矩"),
                ),
                (
                    "torque6",
                    models.FloatField(blank=True, null=True, verbose_name="A6扭矩"),
                ),
                (
                    "torque7",
                    models.FloatField(blank=True, null=True, verbose_name="E7扭矩"),
                ),
                (
                    "fol1",
                    models.FloatField(blank=True, null=True, verbose_name="A1跟随误差"),
                ),
                (
                    "fol2",
                    models.FloatField(blank=True, null=True, verbose_name="A2跟随误差"),
                ),
                (
                    "fol3",
                    models.FloatField(blank=True, null=True, verbose_name="A3跟随误差"),
                ),
                (
                    "fol4",
                    models.FloatField(blank=True, null=True, verbose_name="A4跟随误差"),
                ),
                (
                    "fol5",
                    models.FloatField(blank=True, null=True, verbose_name="A5跟随误差"),
                ),
                (
                    "fol6",
                    models.FloatField(blank=True, null=True, verbose_name="A6跟随误差"),
                ),
                (
                    "fol7",
                    models.FloatField(blank=True, null=True, verbose_name="E7跟随误差"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "机器人轴数据",
                "verbose_name_plural": "机器人轴数据",
                "db_table": "robot_axis_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["part_no", "timestamp"],
                        name="robot_axis__part_no_395a19_idx",
                    ),
                    models.Index(
                        fields=["part_no", "snr_c"],
                        name="robot_axis__part_no_ac2fcd_idx",
                    ),
                ],
            },
        ),
    ]
