# Generated by Django 4.2.20 on 2026-02-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0003_robotaxisdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotcomponent",
            name="level",
            field=models.CharField(
                choices=[("H", "H"), ("M", "M"), ("L", "L"), ("T", "T"), ("C", "C")],
                default="L",
                max_length=1,
                verbose_name="等级",
            ),
        ),
        migrations.CreateModel(
            name="WeeklyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "robot",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="机器人编号"
                    ),
                ),
                (
                    "shop",
                    models.CharField(db_index=True, max_length=64, verbose_name="车间"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="参考编号"
                    ),
                ),
                (
                    "number",
                    models.FloatField(blank=True, null=True, verbose_name="编号"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="类型"
                    ),
                ),
                (
                    "tech",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="工艺"
                    ),
                ),
                ("mark", models.IntegerField(default=0, verbose_name="标记")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "error1_c1",
                    models.FloatField(blank=True, null=True, verbose_name="错误率C1"),
                ),
                (
                    "tem1_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M1"),
                ),
                (
                    "tem2_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M2"),
                ),
                (
                    "tem3_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M3"),
                ),
                (
                    "tem4_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M4"),
                ),
                (
                    "tem5_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M5"),
                ),
                (
                    "tem6_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M6"),
                ),
                (
                    "tem7_m",
                    models.FloatField(blank=True, null=True, verbose_name="温度M7"),
                ),
                (
                    "a1_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A1错误率"),
                ),
                (
                    "a2_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A2错误率"),
                ),
                (
                    "a3_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A3错误率"),
                ),
                (
                    "a4_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A4错误率"),
                ),
                (
                    "a5_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A5错误率"),
                ),
                (
                    "a6_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A6错误率"),
                ),
                (
                    "a7_e_rate",
                    models.FloatField(blank=True, null=True, verbose_name="A7错误率"),
                ),
                (
                    "a1_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A1 RMS"),
                ),
                (
                    "a2_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A2 RMS"),
                ),
                (
                    "a3_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A3 RMS"),
                ),
                (
                    "a4_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A4 RMS"),
                ),
                (
                    "a5_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A5 RMS"),
                ),
                (
                    "a6_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A6 RMS"),
                ),
                (
                    "a7_rms",
                    models.FloatField(blank=True, null=True, verbose_name="A7 RMS"),
                ),
                (
                    "a1_e",
                    models.FloatField(blank=True, null=True, verbose_name="A1 E值"),
                ),
                (
                    "a2_e",
                    models.FloatField(blank=True, null=True, verbose_name="A2 E值"),
                ),
                (
                    "a3_e",
                    models.FloatField(blank=True, null=True, verbose_name="A3 E值"),
                ),
                (
                    "a4_e",
                    models.FloatField(blank=True, null=True, verbose_name="A4 E值"),
                ),
                (
                    "a5_e",
                    models.FloatField(blank=True, null=True, verbose_name="A5 E值"),
                ),
                (
                    "a6_e",
                    models.FloatField(blank=True, null=True, verbose_name="A6 E值"),
                ),
                (
                    "a7_e",
                    models.FloatField(blank=True, null=True, verbose_name="A7 E值"),
                ),
                ("q1", models.FloatField(blank=True, null=True, verbose_name="Q1")),
                ("q2", models.FloatField(blank=True, null=True, verbose_name="Q2")),
                ("q3", models.FloatField(blank=True, null=True, verbose_name="Q3")),
                ("q4", models.FloatField(blank=True, null=True, verbose_name="Q4")),
                ("q5", models.FloatField(blank=True, null=True, verbose_name="Q5")),
                ("q6", models.FloatField(blank=True, null=True, verbose_name="Q6")),
                ("q7", models.FloatField(blank=True, null=True, verbose_name="Q7")),
                (
                    "curr_a1_max",
                    models.FloatField(blank=True, null=True, verbose_name="A1最大电流"),
                ),
                (
                    "curr_a2_max",
                    models.FloatField(blank=True, null=True, verbose_name="A2最大电流"),
                ),
                (
                    "curr_a3_max",
                    models.FloatField(blank=True, null=True, verbose_name="A3最大电流"),
                ),
                (
                    "curr_a4_max",
                    models.FloatField(blank=True, null=True, verbose_name="A4最大电流"),
                ),
                (
                    "curr_a5_max",
                    models.FloatField(blank=True, null=True, verbose_name="A5最大电流"),
                ),
                (
                    "curr_a6_max",
                    models.FloatField(blank=True, null=True, verbose_name="A6最大电流"),
                ),
                (
                    "curr_a7_max",
                    models.FloatField(blank=True, null=True, verbose_name="A7最大电流"),
                ),
                (
                    "curr_a1_min",
                    models.FloatField(blank=True, null=True, verbose_name="A1最小电流"),
                ),
                (
                    "curr_a2_min",
                    models.FloatField(blank=True, null=True, verbose_name="A2最小电流"),
                ),
                (
                    "curr_a3_min",
                    models.FloatField(blank=True, null=True, verbose_name="A3最小电流"),
                ),
                (
                    "curr_a4_min",
                    models.FloatField(blank=True, null=True, verbose_name="A4最小电流"),
                ),
                (
                    "curr_a5_min",
                    models.FloatField(blank=True, null=True, verbose_name="A5最小电流"),
                ),
                (
                    "curr_a6_min",
                    models.FloatField(blank=True, null=True, verbose_name="A6最小电流"),
                ),
                (
                    "curr_a7_min",
                    models.FloatField(blank=True, null=True, verbose_name="A7最小电流"),
                ),
                ("a1", models.FloatField(blank=True, null=True, verbose_name="A1电流")),
                ("a2", models.FloatField(blank=True, null=True, verbose_name="A2电流")),
                ("a3", models.FloatField(blank=True, null=True, verbose_name="A3电流")),
                ("a4", models.FloatField(blank=True, null=True, verbose_name="A4电流")),
                ("a5", models.FloatField(blank=True, null=True, verbose_name="A5电流")),
                ("a6", models.FloatField(blank=True, null=True, verbose_name="A6电流")),
                ("a7", models.FloatField(blank=True, null=True, verbose_name="A7电流")),
                (
                    "p_change",
                    models.FloatField(blank=True, null=True, verbose_name="P变化"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("H", "H"),
                            ("M", "M"),
                            ("L", "L"),
                            ("T", "T"),
                            ("C", "C"),
                        ],
                        default="L",
                        max_length=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(max_length=255, verbose_name="源文件名"),
                ),
                (
                    "week_start",
                    models.DateField(blank=True, null=True, verbose_name="周开始日期"),
                ),
                (
                    "week_end",
                    models.DateField(blank=True, null=True, verbose_name="周结束日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "周结果数据",
                "verbose_name_plural": "周结果数据",
                "db_table": "weekly_results",
                "ordering": ["-updated_at", "robot"],
                "indexes": [
                    models.Index(fields=["robot"], name="weekly_resu_robot_ad6633_idx"),
                    models.Index(fields=["shop"], name="weekly_resu_shop_d11f7a_idx"),
                    models.Index(fields=["level"], name="weekly_resu_level_6e9239_idx"),
                    models.Index(
                        fields=["source_file"], name="weekly_resu_source__805fee_idx"
                    ),
                    models.Index(
                        fields=["week_start", "week_end"],
                        name="weekly_resu_week_st_c64c8f_idx",
                    ),
                ],
            },
        ),
    ]
