# Generated by Django 4.2.20 on 2026-02-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0004_alter_robotcomponent_level_weeklyresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotHighRiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_no",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="部件编号",
                    ),
                ),
                ("group_key", models.CharField(max_length=32, verbose_name="车间Key")),
                (
                    "group_name",
                    models.CharField(max_length=64, verbose_name="车间名称"),
                ),
                (
                    "robot_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="机器人ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="名称"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(max_length=64, verbose_name="参考编号"),
                ),
                ("number", models.IntegerField(default=0, verbose_name="Number")),
                ("type_spec", models.CharField(max_length=128, verbose_name="类型")),
                ("tech", models.CharField(max_length=128, verbose_name="工艺")),
                ("mark", models.IntegerField(default=0, verbose_name="标记")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("checks", models.JSONField(default=dict, verbose_name="A1-A7检查项")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("H", "H"),
                            ("M", "M"),
                            ("L", "L"),
                            ("T", "T"),
                            ("C", "C"),
                        ],
                        default="H",
                        max_length=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                        ],
                        default="online",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "battery",
                    models.PositiveSmallIntegerField(default=100, verbose_name="电量"),
                ),
                (
                    "health",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="健康度"
                    ),
                ),
                (
                    "motor_temp",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="电机温度"
                    ),
                ),
                (
                    "network_latency",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="网络时延"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近上报"
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="风险分数"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        default="high",
                        max_length=16,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_history",
                    models.JSONField(default=list, verbose_name="历史风险记录"),
                ),
                (
                    "snapshot_reason",
                    models.CharField(
                        default="", max_length=255, verbose_name="快照原因"
                    ),
                ),
                (
                    "snapshot_source",
                    models.CharField(
                        default="manual", max_length=64, verbose_name="快照来源"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否生效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="high_risk_snapshots",
                        to="robots.robotcomponent",
                        verbose_name="关联组件",
                    ),
                ),
            ],
            options={
                "verbose_name": "高风险机器人快照",
                "verbose_name_plural": "高风险机器人快照",
                "db_table": "_robot_high_risk_snapshots",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["part_no"], name="Drobot_high_part_no_48b77a_idx"
                    ),
                    models.Index(
                        fields=["robot_id"], name="Drobot_high_robot_i_844c0c_idx"
                    ),
                    models.Index(
                        fields=["group_key"], name="Drobot_high_group_k_1ac92e_idx"
                    ),
                    models.Index(fields=["level"], name="Drobot_high_level_dd7883_idx"),
                    models.Index(
                        fields=["is_active"], name="Drobot_high_is_acti_e6b490_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="Drobot_high_created_bbacdb_idx"
                    ),
                ],
            },
        ),
    ]
