# Generated by Django 4.2.20 on 2026-02-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0006_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighRiskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="部件编号"
                    ),
                ),
                ("group_key", models.CharField(max_length=32, verbose_name="车间Key")),
                (
                    "group_name",
                    models.CharField(max_length=64, verbose_name="车间名称"),
                ),
                (
                    "robot_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="机器人ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="名称"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(max_length=64, verbose_name="参考编号"),
                ),
                ("number", models.IntegerField(default=0, verbose_name="Number")),
                ("type_spec", models.CharField(max_length=128, verbose_name="类型")),
                ("tech", models.CharField(max_length=128, verbose_name="工艺")),
                ("mark", models.IntegerField(default=0, verbose_name="标记")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("checks", models.JSONField(default=dict, verbose_name="A1-A7检查项")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("H", "H"),
                            ("M", "M"),
                            ("L", "L"),
                            ("T", "T"),
                            ("C", "C"),
                        ],
                        default="H",
                        max_length=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                        ],
                        default="online",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "battery",
                    models.PositiveSmallIntegerField(default=100, verbose_name="电量"),
                ),
                (
                    "health",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="健康度"
                    ),
                ),
                (
                    "motor_temp",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="电机温度"
                    ),
                ),
                (
                    "network_latency",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="网络时延"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近上报"
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="风险分数"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        default="high",
                        max_length=16,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "record_source",
                    models.CharField(
                        default="sync", max_length=64, verbose_name="记录来源"
                    ),
                ),
                (
                    "sync_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="同步时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="high_risk_histories",
                        to="robots.robotcomponent",
                        verbose_name="关联组件",
                    ),
                ),
            ],
            options={
                "verbose_name": "历史高风险机器人",
                "verbose_name_plural": "历史高风险机器人",
                "db_table": "high_risk_histories",
                "ordering": ["-created_at", "-sync_time"],
                "indexes": [
                    models.Index(
                        fields=["part_no"], name="high_risk_h_part_no_b6343e_idx"
                    ),
                    models.Index(
                        fields=["robot_id"], name="high_risk_h_robot_i_45630b_idx"
                    ),
                    models.Index(
                        fields=["group_key"], name="high_risk_h_group_k_c86a4d_idx"
                    ),
                    models.Index(fields=["level"], name="high_risk_h_level_c4876e_idx"),
                    models.Index(
                        fields=["-created_at"], name="high_risk_h_created_296ada_idx"
                    ),
                    models.Index(
                        fields=["-sync_time"], name="high_risk_h_sync_ti_95962c_idx"
                    ),
                ],
            },
        ),
    ]
