# Generated by Django 4.2.20 on 2026-02-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0007_highriskhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotcomponent",
            name="a1",
            field=models.FloatField(blank=True, null=True, verbose_name="A1电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a1_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A1 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a1_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A1错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a1_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A1 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a2",
            field=models.FloatField(blank=True, null=True, verbose_name="A2电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a2_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A2 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a2_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A2错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a2_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A2 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a3",
            field=models.FloatField(blank=True, null=True, verbose_name="A3电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a3_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A3 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a3_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A3错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a3_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A3 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a4",
            field=models.FloatField(blank=True, null=True, verbose_name="A4电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a4_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A4 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a4_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A4错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a4_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A4 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a5",
            field=models.FloatField(blank=True, null=True, verbose_name="A5电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a5_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A5 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a5_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A5错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a5_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A5 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a6",
            field=models.FloatField(blank=True, null=True, verbose_name="A6电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a6_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A6 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a6_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A6错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a6_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A6 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a7",
            field=models.FloatField(blank=True, null=True, verbose_name="A7电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a7_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A7 E值"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a7_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A7错误率"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="a7_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A7 RMS"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a1_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A1最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a1_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A1最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a2_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A2最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a2_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A2最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a3_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A3最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a3_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A3最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a4_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A4最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a4_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A4最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a5_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A5最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a5_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A5最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a6_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A6最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a6_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A6最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a7_max",
            field=models.FloatField(blank=True, null=True, verbose_name="A7最大电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="curr_a7_min",
            field=models.FloatField(blank=True, null=True, verbose_name="A7最小电流"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="error1_c1",
            field=models.FloatField(blank=True, null=True, verbose_name="错误率C1"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="p_change",
            field=models.FloatField(blank=True, null=True, verbose_name="P变化"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q1",
            field=models.FloatField(blank=True, null=True, verbose_name="Q1"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q2",
            field=models.FloatField(blank=True, null=True, verbose_name="Q2"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q3",
            field=models.FloatField(blank=True, null=True, verbose_name="Q3"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q4",
            field=models.FloatField(blank=True, null=True, verbose_name="Q4"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q5",
            field=models.FloatField(blank=True, null=True, verbose_name="Q5"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q6",
            field=models.FloatField(blank=True, null=True, verbose_name="Q6"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="q7",
            field=models.FloatField(blank=True, null=True, verbose_name="Q7"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem1_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M1"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem2_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M2"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem3_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M3"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem4_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M4"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem5_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M5"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem6_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M6"),
        ),
        migrations.AddField(
            model_name="robotcomponent",
            name="tem7_m",
            field=models.FloatField(blank=True, null=True, verbose_name="温度M7"),
        ),
    ]
