# Generated by Django 4.2.20 on 2026-02-04 07:15
"""
重建 robot_components 表，严格按照 CSV 字段设计
删除所有不需要的字段，包括 checks 字段
"""

from django.db import migrations, models
import django.utils.timezone


def drop_robot_components_table(apps, schema_editor):
    """删除现有的 robot_components 表"""
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute("SET FOREIGN_KEY_CHECKS = 0;")
        schema_editor.execute("DROP TABLE IF EXISTS robot_components;")
        schema_editor.execute("SET FOREIGN_KEY_CHECKS = 1;")


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0008_add_detailed_fields_to_robot_component"),
    ]

    operations = [
        # 先删除现有的 robot_components 表（禁用事务）
        migrations.RunPython(drop_robot_components_table, migrations.RunPython.noop, atomic=False),

        # 创建新的 robot_components 表
        migrations.CreateModel(
            name='RobotComponent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=models.deletion.RESTRICT, to='robots.robotgroup')),

                # CSV 字段（严格按照顺序）
                ('robot', models.CharField(max_length=64)),
                ('shop', models.CharField(max_length=64, null=True, blank=True)),
                ('reference', models.CharField(max_length=64, null=True, blank=True)),
                ('number', models.FloatField(null=True, blank=True)),
                ('type', models.CharField(max_length=128, null=True, blank=True, db_column='type')),
                ('tech', models.CharField(max_length=128, null=True, blank=True)),
                ('mark', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='')),

                ('error1_c1', models.FloatField(null=True, blank=True)),
                ('tem1_m', models.FloatField(null=True, blank=True)),
                ('tem2_m', models.FloatField(null=True, blank=True)),
                ('tem3_m', models.FloatField(null=True, blank=True)),
                ('tem4_m', models.FloatField(null=True, blank=True)),
                ('tem5_m', models.FloatField(null=True, blank=True)),
                ('tem6_m', models.FloatField(null=True, blank=True)),
                ('tem7_m', models.FloatField(null=True, blank=True)),

                ('a1_e_rate', models.FloatField(null=True, blank=True)),
                ('a2_e_rate', models.FloatField(null=True, blank=True)),
                ('a3_e_rate', models.FloatField(null=True, blank=True)),
                ('a4_e_rate', models.FloatField(null=True, blank=True)),
                ('a5_e_rate', models.FloatField(null=True, blank=True)),
                ('a6_e_rate', models.FloatField(null=True, blank=True)),
                ('a7_e_rate', models.FloatField(null=True, blank=True)),

                ('a1_rms', models.FloatField(null=True, blank=True)),
                ('a2_rms', models.FloatField(null=True, blank=True)),
                ('a3_rms', models.FloatField(null=True, blank=True)),
                ('a4_rms', models.FloatField(null=True, blank=True)),
                ('a5_rms', models.FloatField(null=True, blank=True)),
                ('a6_rms', models.FloatField(null=True, blank=True)),
                ('a7_rms', models.FloatField(null=True, blank=True)),

                ('a1_e', models.FloatField(null=True, blank=True)),
                ('a2_e', models.FloatField(null=True, blank=True)),
                ('a3_e', models.FloatField(null=True, blank=True)),
                ('a4_e', models.FloatField(null=True, blank=True)),
                ('a5_e', models.FloatField(null=True, blank=True)),
                ('a6_e', models.FloatField(null=True, blank=True)),
                ('a7_e', models.FloatField(null=True, blank=True)),

                ('q1', models.FloatField(null=True, blank=True)),
                ('q2', models.FloatField(null=True, blank=True)),
                ('q3', models.FloatField(null=True, blank=True)),
                ('q4', models.FloatField(null=True, blank=True)),
                ('q5', models.FloatField(null=True, blank=True)),
                ('q6', models.FloatField(null=True, blank=True)),
                ('q7', models.FloatField(null=True, blank=True)),

                ('curr_a1_max', models.FloatField(null=True, blank=True)),
                ('curr_a2_max', models.FloatField(null=True, blank=True)),
                ('curr_a3_max', models.FloatField(null=True, blank=True)),
                ('curr_a4_max', models.FloatField(null=True, blank=True)),
                ('curr_a5_max', models.FloatField(null=True, blank=True)),
                ('curr_a6_max', models.FloatField(null=True, blank=True)),
                ('curr_a7_max', models.FloatField(null=True, blank=True)),

                ('curr_a1_min', models.FloatField(null=True, blank=True)),
                ('curr_a2_min', models.FloatField(null=True, blank=True)),
                ('curr_a3_min', models.FloatField(null=True, blank=True)),
                ('curr_a4_min', models.FloatField(null=True, blank=True)),
                ('curr_a5_min', models.FloatField(null=True, blank=True)),
                ('curr_a6_min', models.FloatField(null=True, blank=True)),
                ('curr_a7_min', models.FloatField(null=True, blank=True)),

                ('a1', models.FloatField(null=True, blank=True)),
                ('a2', models.FloatField(null=True, blank=True)),
                ('a3', models.FloatField(null=True, blank=True)),
                ('a4', models.FloatField(null=True, blank=True)),
                ('a5', models.FloatField(null=True, blank=True)),
                ('a6', models.FloatField(null=True, blank=True)),
                ('a7', models.FloatField(null=True, blank=True)),

                ('p_change', models.FloatField(null=True, blank=True)),
                ('level', models.CharField(max_length=1, default='L')),

                # 元数据字段
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'robot_components',
                'db_table_comment': '机器人组件表，严格按照 CSV 字段设计',
            },
        ),
    ]
