# Generated by Django 4.2.20 on 2026-02-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0009_rebuild_robot_components_v2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="robotcomponent",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "机器人组件",
                "verbose_name_plural": "机器人组件",
            },
        ),
        migrations.AlterModelTableComment(
            name="robotcomponent",
            table_comment=None,
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a1",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A1"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a1_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A1_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a1_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A1_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a1_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A1_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a2",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A2"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a2_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A2_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a2_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A2_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a2_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A2_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a3",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A3"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a3_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A3_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a3_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A3_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a3_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A3_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a4",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A4"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a4_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A4_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a4_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A4_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a4_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A4_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a5",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A5"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a5_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A5_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a5_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A5_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a5_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A5_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a6",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A6"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a6_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A6_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a6_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A6_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a6_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A6_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a7",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="A7"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a7_e",
            field=models.FloatField(blank=True, null=True, verbose_name="A7_E"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a7_e_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="A7_e_rate"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a7_rms",
            field=models.FloatField(blank=True, null=True, verbose_name="A7_Rms"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a1_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A1_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a1_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A1_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a2_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A2_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a2_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A2_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a3_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A3_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a3_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A3_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a4_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A4_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a4_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A4_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a5_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A5_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a5_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A5_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a6_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A6_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a6_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A6_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a7_max",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A7_max"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="curr_a7_min",
            field=models.FloatField(blank=True, null=True, verbose_name="Curr_A7_min"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="error1_c1",
            field=models.FloatField(blank=True, null=True, verbose_name="error1_c1"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="components",
                to="robots.robotgroup",
                verbose_name="组",
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="level",
            field=models.CharField(
                choices=[("H", "H"), ("M", "M"), ("L", "L"), ("T", "T"), ("C", "C")],
                default="L",
                max_length=1,
                verbose_name="level",
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="mark",
            field=models.IntegerField(default=0, verbose_name="mark"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="number",
            field=models.FloatField(blank=True, null=True, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="p_change",
            field=models.FloatField(blank=True, null=True, verbose_name="P_Change"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q1",
            field=models.FloatField(blank=True, null=True, verbose_name="Q1"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q2",
            field=models.FloatField(blank=True, null=True, verbose_name="Q2"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q3",
            field=models.FloatField(blank=True, null=True, verbose_name="Q3"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q4",
            field=models.FloatField(blank=True, null=True, verbose_name="Q4"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q5",
            field=models.FloatField(blank=True, null=True, verbose_name="Q5"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q6",
            field=models.FloatField(blank=True, null=True, verbose_name="Q6"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="q7",
            field=models.FloatField(blank=True, null=True, verbose_name="Q7"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="reference",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="reference"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="remark",
            field=models.TextField(blank=True, default="", verbose_name="remark"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="robot",
            field=models.CharField(db_index=True, max_length=64, verbose_name="robot"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="shop",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="shop"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tech",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="tech"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem1_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem1_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem2_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem2_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem3_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem3_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem4_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem4_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem5_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem5_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem6_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem6_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="tem7_m",
            field=models.FloatField(blank=True, null=True, verbose_name="tem7_m"),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="type",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="type"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["robot"], name="robot_compo_robot_d334b5_idx"),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["shop"], name="robot_compo_shop_a0c455_idx"),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["level"], name="robot_compo_level_8964df_idx"),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["group"], name="robot_compo_group_i_df2881_idx"),
        ),
    ]
