# Generated by Django 4.2.20 on 2026-02-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0010_update_a1_a7_to_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotcomponent",
            name="a1",
            field=models.CharField(
                blank=True, db_column="A1", max_length=16, null=True, verbose_name="A1"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a2",
            field=models.CharField(
                blank=True, db_column="A2", max_length=16, null=True, verbose_name="A2"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a3",
            field=models.CharField(
                blank=True, db_column="A3", max_length=16, null=True, verbose_name="A3"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a4",
            field=models.CharField(
                blank=True, db_column="A4", max_length=16, null=True, verbose_name="A4"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a5",
            field=models.CharField(
                blank=True, db_column="A5", max_length=16, null=True, verbose_name="A5"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a6",
            field=models.CharField(
                blank=True, db_column="A6", max_length=16, null=True, verbose_name="A6"
            ),
        ),
        migrations.AlterField(
            model_name="robotcomponent",
            name="a7",
            field=models.CharField(
                blank=True, db_column="A7", max_length=16, null=True, verbose_name="A7"
            ),
        ),
    ]
