# Generated by Django 4.2.20 on 2026-02-04

from django.db import migrations


def rebuild_high_risk_snapshots_table(apps, schema_editor):
    """重建 _robot_high_risk_snapshots 表，使其结构完全等同于 robot_components"""
    with schema_editor.connection.cursor() as cursor:
        # 1. 删除 high_risk_histories 表（如果存在）
        cursor.execute("DROP TABLE IF EXISTS high_risk_histories")

        # 2. 删除现有的 _robot_high_risk_snapshots 表
        cursor.execute("DROP TABLE IF EXISTS _robot_high_risk_snapshots")

        # 3. 创建与 robot_components 完全相同结构的 _robot_high_risk_snapshots 表
        cursor.execute("""
            CREATE TABLE _robot_high_risk_snapshots (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                group_id BIGINT NOT NULL,

                -- CSV 基本字段
                robot VARCHAR(64) NOT NULL,
                shop VARCHAR(64) NULL,
                reference VARCHAR(64) NULL,
                number FLOAT NULL,
                type VARCHAR(128) NULL,
                tech VARCHAR(128) NULL,
                mark INT NOT NULL DEFAULT 0,
                remark TEXT NULL,

                -- 错误率和温度
                error1_c1 FLOAT NULL,
                tem1_m FLOAT NULL,
                tem2_m FLOAT NULL,
                tem3_m FLOAT NULL,
                tem4_m FLOAT NULL,
                tem5_m FLOAT NULL,
                tem6_m FLOAT NULL,
                tem7_m FLOAT NULL,

                -- A1-A7 错误率
                a1_e_rate FLOAT NULL,
                a2_e_rate FLOAT NULL,
                a3_e_rate FLOAT NULL,
                a4_e_rate FLOAT NULL,
                a5_e_rate FLOAT NULL,
                a6_e_rate FLOAT NULL,
                a7_e_rate FLOAT NULL,

                -- A1-A7 RMS
                a1_rms FLOAT NULL,
                a2_rms FLOAT NULL,
                a3_rms FLOAT NULL,
                a4_rms FLOAT NULL,
                a5_rms FLOAT NULL,
                a6_rms FLOAT NULL,
                a7_rms FLOAT NULL,

                -- A1-A7 E值
                a1_e FLOAT NULL,
                a2_e FLOAT NULL,
                a3_e FLOAT NULL,
                a4_e FLOAT NULL,
                a5_e FLOAT NULL,
                a6_e FLOAT NULL,
                a7_e FLOAT NULL,

                -- Q1-Q7
                q1 FLOAT NULL,
                q2 FLOAT NULL,
                q3 FLOAT NULL,
                q4 FLOAT NULL,
                q5 FLOAT NULL,
                q6 FLOAT NULL,
                q7 FLOAT NULL,

                -- 最大电流
                curr_a1_max FLOAT NULL,
                curr_a2_max FLOAT NULL,
                curr_a3_max FLOAT NULL,
                curr_a4_max FLOAT NULL,
                curr_a5_max FLOAT NULL,
                curr_a6_max FLOAT NULL,
                curr_a7_max FLOAT NULL,

                -- 最小电流
                curr_a1_min FLOAT NULL,
                curr_a2_min FLOAT NULL,
                curr_a3_min FLOAT NULL,
                curr_a4_min FLOAT NULL,
                curr_a5_min FLOAT NULL,
                curr_a6_min FLOAT NULL,
                curr_a7_min FLOAT NULL,

                -- A1-A7 状态字符串
                A1 VARCHAR(16) NULL,
                A2 VARCHAR(16) NULL,
                A3 VARCHAR(16) NULL,
                A4 VARCHAR(16) NULL,
                A5 VARCHAR(16) NULL,
                A6 VARCHAR(16) NULL,
                A7 VARCHAR(16) NULL,

                -- 其他
                p_change FLOAT NULL,
                level VARCHAR(1) NOT NULL DEFAULT 'L',

                -- 元数据
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                -- 索引
                INDEX idx_robot (robot),
                INDEX idx_shop (shop),
                INDEX idx_level (level),
                INDEX idx_group (group_id),
                INDEX idx_created_at (created_at),

                -- 外键约束
                FOREIGN KEY (group_id) REFERENCES robot_groups(id) ON DELETE RESTRICT
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0011_rename_a1_a7_to_uppercase"),
    ]

    operations = [
        migrations.RunPython(rebuild_high_risk_snapshots_table, atomic=False),
    ]
