# Generated by Django 4.2.20 on 2026-02-04

from django.db import migrations, models


def update_weeklyresult_a1_a7_to_string(apps, schema_editor):
    """更新 weekly_results 表的 A1-A7 字段为字符串类型"""
    with schema_editor.connection.cursor() as cursor:
        # 修改 A1-A7 字段为 VARCHAR
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A1 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A2 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A3 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A4 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A5 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A6 VARCHAR(16) NULL")
        cursor.execute("ALTER TABLE weekly_results MODIFY COLUMN A7 VARCHAR(16) NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0012_rebuild_high_risk_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyresult",
            name="a1",
            field=models.CharField(
                blank=True, db_column="A1", max_length=16, null=True, verbose_name="A1"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a2",
            field=models.CharField(
                blank=True, db_column="A2", max_length=16, null=True, verbose_name="A2"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a3",
            field=models.CharField(
                blank=True, db_column="A3", max_length=16, null=True, verbose_name="A3"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a4",
            field=models.CharField(
                blank=True, db_column="A4", max_length=16, null=True, verbose_name="A4"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a5",
            field=models.CharField(
                blank=True, db_column="A5", max_length=16, null=True, verbose_name="A5"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a6",
            field=models.CharField(
                blank=True, db_column="A6", max_length=16, null=True, verbose_name="A6"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyresult",
            name="a7",
            field=models.CharField(
                blank=True, db_column="A7", max_length=16, null=True, verbose_name="A7"
            ),
        ),
        migrations.RunPython(update_weeklyresult_a1_a7_to_string, atomic=False),
    ]
