# Generated by Django 4.2.20 on 2026-02-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0014_drop_weekly_results_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    )
                ),
                ("source", models.CharField(
                    choices=[("manual", "手动同步"), ("auto", "自动同步")],
                    default="manual",
                    max_length=16,
                    verbose_name="数据来源"
                )),
                ("status", models.CharField(
                    choices=[("success", "成功"), ("failed", "失败")],
                    default="success",
                    max_length=16,
                    verbose_name="状态"
                )),
                ("source_file", models.CharField(
                    blank=True,
                    default="",
                    max_length=255,
                    verbose_name="源文件名"
                )),
                ("file_date", models.DateField(
                    blank=True,
                    null=True,
                    verbose_name="文件日期"
                )),
                ("records_created", models.PositiveIntegerField(
                    default=0,
                    verbose_name="新增记录数"
                )),
                ("records_updated", models.PositiveIntegerField(
                    default=0,
                    verbose_name="更新记录数"
                )),
                ("records_deleted", models.PositiveIntegerField(
                    default=0,
                    verbose_name="删除记录数"
                )),
                ("total_records", models.PositiveIntegerField(
                    default=0,
                    verbose_name="总记录数"
                )),
                ("error_message", models.TextField(
                    blank=True,
                    default="",
                    verbose_name="错误信息"
                )),
                ("sync_time", models.DateTimeField(
                    auto_now_add=True,
                    verbose_name="同步时间"
                )),
            ],
            options={
                "verbose_name": "刷新日志",
                "verbose_name_plural": "刷新日志",
                "db_table": "refresh_logs",
                "ordering": ["-sync_time"],
                "indexes": [
                    models.Index(fields=["-sync_time"], name="robots_ref_sync_time_idx"),
                    models.Index(fields=["source"], name="robots_ref_source_idx"),
                    models.Index(fields=["status"], name="robots_ref_status_idx"),
                ],
            },
        ),
    ]
